FsegaManagement/FsegaManagement/Controllers/TipConcediiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FsegaManagement.Data;
using AutoMapper;
using FsegaManagement.Models;
using FsegaManagement.Interfaces;
using Microsoft.AspNetCore.Authorization;

namespace FsegaManagement.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TipConcediiController : Controller
    {
        private readonly IManagementTypeRepo managementTypeRepo;
        private readonly IMapper mapper;
        public TipConcediiController(IManagementTypeRepo managementTypeRepo, IMapper mapper)
        {
            this.managementTypeRepo = managementTypeRepo;
            this.mapper = mapper;
        }

        // GET: TipConcedii
        public async Task<IActionResult> Index()
        {

            var tipConcedii = mapper.Map<List<TipConcediuViewModel>>(await managementTypeRepo.GetAllAsync());
              return View(tipConcedii);
        }

        // GET: TipConcedii/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            var tipConcediu = await managementTypeRepo.GetAsync(id);
            if (tipConcediu == null)
            {
                return NotFound();
            }
            var tipConcediuViewModel = mapper.Map<TipConcediuViewModel>(tipConcediu);
            return View(tipConcediuViewModel);
        }

        // GET: TipConcedii/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TipConcedii/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TipConcediuViewModel tipConcediuViewModel)
        {
            if (ModelState.IsValid)
            {
                var tipConcediu = mapper.Map<TipConcediu>(tipConcediuViewModel);
                await managementTypeRepo.AddAsync(tipConcediu);
                return RedirectToAction(nameof(Index));
            }
            return View(tipConcediuViewModel);
        }

        // GET: TipConcedii/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var tipConcediu = await managementTypeRepo.GetAsync(id);
            if (tipConcediu == null)
            {
                return NotFound();
            }
            var tipConcediuViewModel = mapper.Map<TipConcediuViewModel>(tipConcediu);
            return View(tipConcediuViewModel);
        }

        // POST: TipConcedii/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, TipConcediuViewModel tipConcediuViewModel)
        {
            if (id != tipConcediuViewModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var tipConcediu = mapper.Map<TipConcediu>(tipConcediuViewModel);
                    await managementTypeRepo.UpdateAsync(tipConcediu);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await managementTypeRepo.Exists(tipConcediuViewModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tipConcediuViewModel);
        }

        // POST: TipConcedii/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await managementTypeRepo.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

FsegaManagement/FsegaManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FsegaManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.2/css/dataTables.bootstrap5.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FsegaManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fsega: Concedii Angajati</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipConcedii" asp-action="Create">Cerere Concediu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipConcedii" asp-action="Index">Concediul Meu</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now - Fsega: Concedii Angajati - <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/sweetalert/"></script>
    <script src="https://cdn.datatables.net/1.13.2/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.2/js/dataTables.bootstrap5.min.js"></script>  
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>